### ISSUE TITLE
High magnification resolution - bad fit

### ISSUE THREAD

**Issue by Noitidart** [1yzo/todo#18]
Things are not fitting so well. I have resolution setto 150% on my laptop so things are easy to read. It's not working good with fit:

<img width="1019" alt="screen shot 2018-11-19 at 10 11 06 am" src="https://user-images.githubusercontent.com/6372489/48726212-8538dd00-ebe3-11e8-9a52-8b1a14b686f8.png">

**Comment by 1yzo** [comment]
oh dang yeah I dunno why i gave a fixed width to the item containers. Ill change that iA.

**Comment by Noitidart** [comment]
low priority
